Identity service
Hostileca/Social-network pull request #1
Opened 2024-08-29 12:17 UTC by Hostileca

2024-08-30 14:08 UTC, MefistoSamael requested changes

2024-08-30 14:08 UTC, MefistoSamael commented on Backend/IdentityService/BusinessLogicLayer/Services/Interfaces/IAuthService.cs
> +    Task<Results> LoginAsync(LoginViewModel loginViewModel);
empty lines between methods

2024-08-30 14:08 UTC, MefistoSamael commented on Backend/IdentityService/BusinessLogicLayer/BusinessLogicLayer.csproj
> +      <ProjectReference Include="..\DataAccessLayer\DataAccessLayer.csproj" />
business logic layer must not to have dependencies on DAL

2024-08-30 14:08 UTC, MefistoSamael commented on Backend/IdentityService/DataAccessLayer/Models/User.cs
> +}
place user in bll

2024-08-30 18:52 UTC, Hostileca commented on Backend/IdentityService/BusinessLogicLayer/BusinessLogicLayer.csproj
> +      <ProjectReference Include="..\DataAccessLayer\DataAccessLayer.csproj" />
So, if I place models in bll, DAL will have dependencies on BL. Is it correct?

2024-09-02 11:33 UTC, MefistoSamael commented on Backend/IdentityService/BusinessLogicLayer/Exceptions/DuplicateException.cs
rename it to alreadyexists

2024-09-02 11:33 UTC, MefistoSamael commented on Backend/IdentityService/BusinessLogicLayer/Exceptions/AuthorizationException.cs
rename to unauthorized

2024-09-02 11:33 UTC, MefistoSamael commented on Backend/IdentityService/BusinessLogicLayer/Services/Implementations/AccountService.cs
> +        var newUser = new User { UserName = userRegisterDto.Username, Email = userRegisterDto.Email };
use mapper

2024-09-02 11:33 UTC, MefistoSamael commented on Backend/IdentityService/BusinessLogicLayer/Services/Implementations/AccountService.cs
> +            throw new AuthorizationException("User creation failed");
are you sure that it is unauthorized?

2024-09-02 11:33 UTC, MefistoSamael commented on Backend/IdentityService/BusinessLogicLayer/Services/Implementations/AccountService.cs
> +        }
all conditional statements must me preceeded and followed by blank lines

2024-09-02 11:33 UTC, MefistoSamael commented on Backend/IdentityService/DataAccessLayer/Models/User.cs
move to business logic layer

2024-09-02 11:33 UTC, MefistoSamael commented on Backend/IdentityService/DataAccessLayer/Models/User.cs
move to business logic layer

2024-09-02 11:35 UTC, MefistoSamael requested changes
Add jwt/refresh tokens. Add user crud

2024-09-05 17:40 UTC, MefistoSamael approved these changes

2024-09-06 06:51 UTC, merged